dist: trusty
language: python
notifications:
  email: false
cache:
  pip: true
matrix:
  include:
    - python: 2.7
    - os: osx
      osx_image: xcode9.1
      language: generic
      before_install:
      - virtualenv env
      - source env/bin/activate
install:
  - pip install nose tensorflow==1.4.0
  - pip install -e .
script:
  - python scripts/download_weights.py
  - cd tests
  - nosetests -v
